version: 2.1
orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  docker: circleci/docker@2.2.0
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker Image
          command: docker build -t ebaymail93/corsodocker -f Dockerfile.dev .
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Deploy to Elastic Beanstalk
          command: |
            pip install awsebcli
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            eb deploy CorsoDockerCircleCI-env

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build