version: 2.1
orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  docker: circleci/docker@2.2.0
jobs:
  build:
    executor: docker/default
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t ebaymail93/corsodocker -f Dockerfile .
      - docker/save-image:
          name: Save Docker Image
          image_name: ebaymail93/corsodocker
          tag: circleci-react
  deploy:
    executor: aws-elasticbeanstalk/default
    steps:
      - aws-elasticbeanstalk/deploy:
          application: Corso Docker CircleCI
          environment: CorsoDockerCircleCI-env
          image_path: ebaymail93/corsodocker:circleci-react

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build