version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.6.0-browsers
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Build the image"
          command: "docker build -t ebaymail93/corsodocker:circleci-react -f Dockerfile.dev ."
      - run:
          name: "Run tests"
          command: "docker run -e CI=true ebaymail93/corsodocker:circleci-react npm run test"  
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Deploy to Elastic Beanstalk
          command: |
            pip install awsebcli
            aws configure set aws_access_key_id $AWS_ACCESS_KEY
            aws configure set aws_secret_access_key $AWS_SECRET_KEY
            eb deploy CorsoDockerCircleCI-env
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build