branch-defaults:
  master:
    environment: Corso Docker CircleCI-$CIRCLECI_BRANCH
  develop:
    environment:  Corso Docker CircleCI-$CIRCLECI_BRANCH
global:
  application_name:  Corso Docker CircleCI
  default_platform: 64bit Amazon Linux 2023/4.0.0
  default_region: us-east-1
  sc: git