version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
  docker: circleci/docker@2.2.0
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker Image
          command: docker build -t ebaymail93/corsodocker -f Dockerfile.dev .
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
    - checkout
    - eb/setup
    - run:
        name: Deploy to Elastic Beanstalk
        command: |
          eb deploy CorsoDockerCircleCI-env

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
